# Gitpod configuration file
image: ./Dockerfile

tasks:
  - name: setup-environment
    init: |
      echo "Setting up environment..."
      ./aws/bin/aws_cli_install.sh
      ./aws/bin/terraform_cli_install.sh
      cd aws/s3/sdk/Python
      python3 -m venv python_venv
      source python_venv/bin/activate
      pip install boto3
    command: |
      echo "Environment setup complete!"
  - name: verify-setup
    command: |
      echo "Verifying AWS CLI..."
      aws --version
      aws sts get-caller-identity
      echo "AWS CLI setup verified."

# Specify prebuilds for faster startup
prebuilds:
  master: true

# Environment variables for AWS credentials
# Replace these with real values in Gitpod Dashboard (to keep secrets safe)
vscode:
  extensions:
    - ms-python.python
    - hashicorp.terraform


