# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: setup-aws-cli
    init: |
      cd /workspace
      curl -O https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT






