# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: setup-aws-cli
    init: |
      cd /workspace
      curl -O https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      unzip awscli-exe-linux-x86_64.zip
      sudo ./aws/install --no-sign-request
      cd $THEIA_WORKSPACE_ROOT
      aws configure set region us-east-1
      aws configure set output json









