tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk 

  - name: terraform
    before: |
      ./workspaces/aws-solutions-architect/aws/bin/terraform_cli_install.sh

  - name: setup-aws-cli
    init: |
      ./workspaces/aws-solutions-architect/aws/bin/aws_cli_install.sh

  - name: setup-python-env
    init: |
      cd aws/s3/sdk/Python
      python -m venv python_venv
      . python_venv/bin/activate
      pip install boto3

  - name: configure-bashrc
    init: |
      echo 'cd_func () {' >> ~/.bashrc
      echo '  builtin cd "$@"' >> ~/.bashrc
      echo '  if [[ "$PWD" == */aws/s3/sdk/Python ]]; then' >> ~/.bashrc
      echo '    if [ -d "python_venv" ]; then' >> ~/.bashrc
      echo '      echo "Activating virtual environment in $PWD"' >> ~/.bashrc
      echo '      . python_venv/bin/activate' >> ~/.bashrc
      echo '    fi' >> ~/.bashrc
      echo '  fi' >> ~/.bashrc
      echo '}' >> ~/.bashrc
      echo 'alias cd="cd_func"' >> ~/.bashrc
      source ~/.bashrc
