#!/usr/bin/env bash

# delete-objects.sh - Delete one or more objects from an S3 bucket
#
# Usage: ./delete-objects.sh <bucket-name> <file-name1> [<file-name2> ...]
#
# This script deletes the specified files from the given S3 bucket.
# Ensure you have AWS CLI configured with the necessary permissions to access S3.

# Check if a bucket name is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name> <file-name1> [<file-name2> ...]"
  exit 1
fi

bucket_name=$1
shift  # Remove the bucket name from the list of arguments

# Loop through all provided file names and delete them
for file_name in "$@"; do
  if [ -n "$file_name" ]; then
    echo "Deleting $file_name from bucket: $bucket_name"
    aws s3 rm "s3://$bucket_name/$file_name"
  else
    echo "No file name provided to delete."
  fi
done
